name: sandbox
description: "A new Flutter project."
# 以下行防止包被意外发布到pub.dev
# 使用 `flutter pub publish`。这对于私有包是首选。
publish_to: 'none' # 如果您希望发布到pub.dev，请删除此行

# 以下定义了应用程序的版本号和构建号。
# 版本号是三个用点分隔的数字，如1.2.43
# 后跟一个可选的构建号，用+分隔。
# 版本号和构建号都可以在flutter构建中通过指定--build-name和--build-number来覆盖。
# 在Android中，build-name用作versionName，而build-number用作versionCode。
# 有关Android版本控制的更多信息，请参阅https://developer.android.com/studio/publish/versioning
# 在iOS中，build-name用作CFBundleShortVersionString，而build-number用作CFBundleVersion。
# 有关iOS版本控制的更多信息，请参阅
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# 在Windows中，build-name用作产品和文件版本的主要、次要和补丁部分
# 而build-number用作构建后缀。
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# 依赖项指定您的包需要工作的其他包。
# 要自动升级您的包依赖项到最新版本
# 考虑运行 `flutter pub upgrade --major-versions`。或者，
# 可以通过将下面的版本号更改为pub.dev上可用的最新版本来手动更新依赖项。
# 要查看哪些依赖项有更新的版本可用，请运行 `flutter pub outdated`。
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  
  # 以下将Cupertino Icons字体添加到您的应用程序中。
  # 与CupertinoIcons类一起使用以获取iOS风格的图标。
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 下面的"flutter_lints"包包含一组推荐的lint规则
  # 以鼓励良好的编码实践。该包提供的lint集
  # 在您的包根目录下的`analysis_options.yaml`文件中激活。
  # 有关停用特定lint规则和激活其他规则的信息，请参阅该文件。
  flutter_lints: ^5.0.0

# 有关此文件的通用Dart部分的信息，请参阅
# 以下页面：https://dart.dev/tools/pub/pubspec
# 以下部分特定于Flutter包。
flutter:

  # 以下行确保Material Icons字体
  # 包含在您的应用程序中，以便您可以使用
  # material Icons类中的图标。
  uses-material-design: true
  # 要向应用程序添加资源，请添加一个assets部分，如下所示：
  assets:
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # 图像资源可以引用一个或多个分辨率特定的"变体"，请参阅
  # https://flutter.dev/to/resolution-aware-images
  # 有关从包依赖项添加资源的详细信息，请参阅
  # https://flutter.dev/to/asset-from-package
  # 要向应用程序添加自定义字体，请在此处添加fonts部分，
  # 在此"flutter"部分中。列表中的每个条目都应具有
  # 一个"family"键，其中包含字体家族名称，以及一个"fonts"键，其中包含
  # 一个给出字体资源和其它描述符的列表。例如：
#  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 有关从包依赖项添加字体的详细信息，
  # 请参阅 https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
